theme: jekyll-theme-slate
title: jrummell.ToString()
description: Another .NET blog
google_analytics: UA-20232883-1
comments: true
twitter_username: jrummell
github_username:  jrummell
page_paths: [archive.md, tags.md, projects.md]
disqus_shortname: jrummell
exclude: ["*.ps1", "Gemfile*", "vendor/"]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      permalink: /:slug
      layout: post
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
repository: jrummell/jrummell.github.io
